FROM mysql:8.0

# Set environment variables for MySQL
ENV MYSQL_DATABASE penguin_db
ENV MYSQL_USER root 
ENV MYSQL_PASSWORD 98Microne$
ENV MYSQL_ROOT_PASSWORD 98Microne$

# Expose port 3306 for MySQL
EXPOSE 5432

